spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:~/cafeOrderApplication
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
